#!/bin/bash

set -eu


## works both under bash and sh
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")


cd $SCRIPT_DIR


echo "disabling keys"

##echo $XDG_CURRENT_DESKTOP
## kde: KDE


x_env=0
sleep_button_state=""

echo "Current X env: $XDG_CURRENT_DESKTOP"

if [ "$XDG_CURRENT_DESKTOP" == "KDE" ]; then
    echo "kde detected"
    x_env="kde"
elif [ "$XDG_CURRENT_DESKTOP" == "XFCE" ]; then
    echo "xfce detected"
    x_env="xfce4"
fi


if [ "$x_env" == "kde" ]; then
    sleep_button_state=$(kreadconfig5 --file kglobalshortcutsrc --group org_kde_powerdevil --key=Sleep)
    echo "Sleep global hotkey state: $sleep_button_state"
    ## disable button
    kwriteconfig5 --file kglobalshortcutsrc --group org_kde_powerdevil --key=Sleep "none,Sleep,Suspend"
    ## reconfigure does not work
    qdbus org.kde.KWin /KWin reconfigure
elif [ "$x_env" == "xfce4" ]; then
    sleep_button_state=$(xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/sleep-button-action)
    echo "power manager sleep button state: $sleep_button_state"
    ## disable button
    xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/sleep-button-action -s 0
fi
 
XMODMAP_BACKUP_CONF=$SCRIPT_DIR/../tmp/xmodmap_backup.txt
xmodmap -pke > $XMODMAP_BACKUP_CONF

XMODMAP_DISABLED_CONF=$SCRIPT_DIR/xmodmap_block.txt
xmodmap $XMODMAP_DISABLED_CONF


echo "starting the app"

exit_code=0
python3 -m littleted "$@" && exit_code=$? || exit_code=$?

if [ $exit_code -ne 0 ]; then
    echo "abnormal application exit: $exit_code"
fi


echo "restoring keys settings"

xmodmap $XMODMAP_BACKUP_CONF

if [ "$x_env" == "kde" ]; then
    kwriteconfig5 --file kglobalshortcutsrc --group org_kde_powerdevil --key=Sleep "$sleep_button_state"
    ## reconfigure does not work
    qdbus org.kde.KWin /KWin reconfigure
elif [ "$x_env" == "xfce4" ]; then
    xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/sleep-button-action -s $sleep_button_state
fi

echo "Done"
