#!/bin/bash

set -eu


## works both under bash and sh
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")


cd $SCRIPT_DIR


echo "disabling keys"

sleep_state=$(xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/sleep-button-action)
echo "power manager sleep button state: $sleep_state"

xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/sleep-button-action -s 0
 
XMODMAP_BACKUP_CONF=$SCRIPT_DIR/../tmp/xmodmap_backup.txt
xmodmap -pke > $XMODMAP_BACKUP_CONF

XMODMAP_DISABLED_CONF=$SCRIPT_DIR/xmodmap_block.txt
xmodmap $XMODMAP_DISABLED_CONF


echo "starting the app"

python3 -m littleted "$@" && exit_code=$? || exit_code=$?


if [ $exit_code -ne 0 ]; then
    echo "abnormal application exit: $exit_code"
fi


echo "restoring keys settings"

xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/sleep-button-action -s $sleep_state

xmodmap $XMODMAP_BACKUP_CONF

echo "Done"
